/**
 * build.js — Cache-busting build script for GitHub Pages deployment.
 *
 * 职责：
 *   1. 为所有本地资源（CSS / JS / 图片等）追加版本号查询参数，
 *      浏览器看到 URL 变化就会拉新内容。
 *   2. 注入 Service Worker 注册脚本到每个 HTML 页面。
 *   3. 生成 sw.js（VERSION 由本次 build 决定），浏览器发现字节变化
 *      会自动 install 新 SW，清掉旧缓存。
 *
 * 不再做 location.replace 强加重定向——那种做法污染 URL、干扰导航、
 * 且对 GitHub Pages 静态文件的缓存行为没有实质帮助。改由 SW 统一接管。
 *
 * Usage:
 *   node build.js              # adds date-based version
 *   node build.js --git        # uses git commit hash (requires git)
 *   node build.js --dry         # preview changes without writing
 *   node build.js --fresh       # force refresh (adds timestamp)
 *
 * After running, commit and push the updated HTML files + sw.js.
 */

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Parse arguments
const isDry    = process.argv.includes('--dry');
const useGit   = process.argv.includes('--git');
const forceFresh = process.argv.includes('--fresh');

// Generate version string
let version;
if (forceFresh) {
  version = Date.now().toString();
  console.log('Using timestamp-based version for forced refresh');
} else if (useGit) {
  try {
    version = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
    console.log(`Using git commit hash: ${version}`);
  } catch (e) {
    console.warn('Git not available, falling back to date-based version');
    version = getDateVersion();
  }
} else {
  version = getDateVersion();
  console.log(`Using date-based version: ${version}`);
}

function getDateVersion() {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm   = String(now.getMonth() + 1).padStart(2, '0');
  const dd   = String(now.getDate()).padStart(2, '0');
  return `${yyyy}${mm}${dd}`;
}

// 之前用过的、会被旧脚本注入到 <head> 里的内联 cache-buster 文本。
// 这里保留一份常量，仅用于从已存在的 HTML 中清理残留（升级到本版本时执行一次）。
const LEGACY_FORCE_FRESH_MARKER = '__pageLoaded';
const LEGACY_FORCE_FRESH_PATTERN = new RegExp(
  '<script>\\s*\\(function\\(\\) \\{[^<]*?__pageLoaded[\\s\\S]*?location\\.replace[\\s\\S]*?\\}\\)\\(\\);\\s*<\\/script>\\s*',
  'g'
);

// File extensions that need cache busting
const RESOURCE_EXTENSIONS = ['.css', '.js', '.webp', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico'];

// Directories to scan for HTML files
const HTML_DIRS = [
  path.join(__dirname),
  path.join(__dirname, 'en'),
  path.join(__dirname, 'guide'),
  path.join(__dirname, 'components'),
];

// ===== Service Worker 模板 =====
// 策略：纯网络模式（network-only）。
// - 所有同源 GET 请求一律先打网络，**不读缓存**也**不写缓存**。
// - 网络挂了直接返回 503，浏览器渲染错误页或资源失败——绝不显示旧版本。
// - 任何 HTML / CSS / JS / 图片更新后，用户下次访问必看到最新版。
const SW_TEMPLATE = `// sw.js — Service Worker for Ocelot Sign Mod Wiki
// AUTO-GENERATED by build.js. 不要手动改下面这行 VERSION。
// 当 build.js 替换 VERSION 时，浏览器检测到字节变化 → install 新 SW。
const VERSION = '__SW_VERSION__';

self.addEventListener('install', (event) => {
  // 新 SW 立即激活，不等旧 tab 关闭
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // 清掉旧版本残留的缓存（纯网络模式不再写新缓存，但要把旧的擦干净）
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((k) => k.startsWith('ocelot-wiki-'))
        .map((k) => {
          console.log('[SW] delete old cache:', k);
          return caches.delete(k);
        })
    );
    // 立即接管所有已打开的 tab
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // 只处理同源 GET 请求
  if (request.method !== 'GET') return;
  if (url.origin !== self.location.origin) return;

  // 跳过 SW 自身，避免循环
  if (url.pathname.endsWith('/sw.js')) return;

  // 纯网络模式：永远先打网络，不读缓存也不写缓存
  event.respondWith(
    fetch(request).catch(() => {
      const accept = request.headers.get('accept') || '';
      const isHTML = request.mode === 'navigate' || accept.includes('text/html');

      if (isHTML) {
        // HTML 返回一个友好的离线错误页（让用户知道发生了什么）
        const html = '<!DOCTYPE html>\\n<html lang="zh-CN">\\n<head>\\n' +
          '<meta charset="UTF-8">\\n' +
          '<meta name="viewport" content="width=device-width, initial-scale=1.0">\\n' +
          '<title>网络不可用 | 豹猫指示牌模组</title>\\n' +
          '<style>\\n' +
          'body { font-family: "Microsoft YaHei", sans-serif; background: #1a1a2e; color: #ccc;\\n' +
          '       display: flex; flex-direction: column; align-items: center; justify-content: center;\\n' +
          '       min-height: 100vh; margin: 0; text-align: center; padding: 20px; }\\n' +
          'h1 { font-size: 48px; color: #f0a500; margin: 0 0 16px; }\\n' +
          'p { font-size: 16px; margin: 0 0 24px; }\\n' +
          'button { background: #4a90d9; border: 0; padding: 12px 24px; color: #fff;\\n' +
          '        border-radius: 4px; cursor: pointer; font-size: 16px; }\\n' +
          'button:hover { background: #5aa0e9; }\\n' +
          '</style>\\n</head>\\n<body>\\n' +
          '<h1>网络连接失败</h1>\\n' +
          '<p>无法连接到 GitHub Pages。请检查网络后重试。</p>\\n' +
          '<button onclick="location.reload()">刷新页面</button>\\n' +
          '</body>\\n</html>';
        return new Response(html, {
          status: 503,
          statusText: 'Service Unavailable',
          headers: { 'Content-Type': 'text/html; charset=utf-8' }
        });
      }

      // 静态资源（CSS / JS / 图片）失败：返回 503 文本
      return new Response('Network unavailable', {
        status: 503,
        statusText: 'Service Unavailable',
        headers: { 'Content-Type': 'text/plain; charset=utf-8' }
      });
    })
  );
});
`;

// ===== SW 注册脚本（注入到每个 HTML 的 </body> 之前） =====
// 不写死相对路径——而是先找到 components.js 算出站点根，再拼 sw.js 路径。
// 这样在 GitHub Pages (/OcelotSignMod_Docs/) 和本地 (/) 都能正确注册。
const SW_REGISTRATION_SCRIPT = `(function() {
  if (!('serviceWorker' in navigator)) return;

  function detectSwPath() {
    // 通过 components.js 的 src 推算站点根
    var scripts = document.getElementsByTagName('script');
    for (var i = 0; i < scripts.length; i++) {
      var src = scripts[i].src || '';
      if (src.indexOf('components.js') !== -1) {
        try {
          var u = new URL(src);
          var segs = u.pathname.split('/').filter(Boolean);
          segs.pop(); // components.js
          segs.pop(); // js
          return (segs.length === 0 ? '/' : '/' + segs.join('/') + '/') + 'sw.js';
        } catch (e) { /* fall through */ }
      }
    }
    return 'sw.js';
  }

  function register() {
    navigator.serviceWorker.register(detectSwPath()).then(function(reg) {
      // 定时检查更新（30 分钟），用户长时间停留时也能拉到新版
      setInterval(function() { reg.update().catch(function() {}); }, 30 * 60 * 1000);
      // 切回标签页时也检查一次
      document.addEventListener('visibilitychange', function() {
        if (!document.hidden) reg.update().catch(function() {});
      });
    }).catch(function(err) {
      console.warn('[SW] registration failed:', err);
    });
  }

  if (document.readyState === 'complete') {
    register();
  } else {
    window.addEventListener('load', register);
  }
})();`;

// Find all HTML files recursively
function findHtmlFiles(dir) {
  const files = [];
  if (!fs.existsSync(dir)) return files;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      // Skip node_modules, .git, dist, build directories
      if (!['node_modules', '.git', 'dist', 'build'].includes(entry.name)) {
        files.push(...findHtmlFiles(fullPath));
      }
    } else if (entry.name.endsWith('.html') || entry.name.endsWith('.htm')) {
      files.push(fullPath);
    }
  }
  return files;
}

// Check if a URL needs cache busting
function needsCacheBust(url) {
  // Skip external URLs and anchor-only links
  if (!url || url.startsWith('http://') || url.startsWith('https://') ||
      url.startsWith('//') || url.startsWith('mailto:') || url.startsWith('#')) {
    return false;
  }

  // Check if it references a local resource that needs cache busting
  const ext = path.extname(url.split('?')[0]).toLowerCase();
  return RESOURCE_EXTENSIONS.includes(ext);
}

// Add version query parameter to a URL
function addVersion(url) {
  const [pathPart, queryPart] = url.split('?');
  const separator = queryPart ? '&' : '?';
  return `${pathPart}${separator}v=${version}`;
}

// Process HTML file content
function processHtml(content) {
  let result = content;

  // 1. 清理旧版本残留的强制刷新内联脚本（如果存在）。
  if (result.includes(LEGACY_FORCE_FRESH_MARKER)) {
    result = result.replace(LEGACY_FORCE_FRESH_PATTERN, '');
  }

  // 2. 为本地资源（CSS / JS / 图片）追加或更新 ?v=<version> 参数。
  const attrPattern = /(href|src)="([^"]+)"/gi;
  result = result.replace(attrPattern, (match, attr, url) => {
    if (!needsCacheBust(url)) return match;
    const [pathPart, queryPart = ''] = url.split('?');
    const params = new URLSearchParams(queryPart);
    params.set('v', version);
    const newQuery = params.toString();
    return `${attr}="${pathPart}?${newQuery}"`;
  });

  // 3. 注入 SW 注册脚本到 </body> 之前（仅注入一次）。
  if (!result.includes("'serviceWorker' in navigator")) {
    const bodyClosePattern = /<\/body>/i;
    if (bodyClosePattern.test(result)) {
      const inject = `<script>\n${SW_REGISTRATION_SCRIPT}\n</script>\n</body>`;
      result = result.replace(bodyClosePattern, inject);
    }
  }

  return result;
}

// 生成 sw.js 文件
function writeServiceWorker() {
  const swContent = SW_TEMPLATE.replace('__SW_VERSION__', version);
  const swPath = path.join(__dirname, 'sw.js');
  if (isDry) {
    console.log(`  (would write) sw.js  (?v=${version})`);
    return;
  }
  fs.writeFileSync(swPath, swContent, 'utf8');
  console.log(`  sw.js  (VERSION=${version})`);
}

// Find all HTML files
const htmlFiles = [];
for (const dir of HTML_DIRS) {
  htmlFiles.push(...findHtmlFiles(dir));
}

// Remove duplicates
const uniqueFiles = [...new Set(htmlFiles)];

console.log(`\nFound ${uniqueFiles.length} HTML files to process\n`);

let processed = 0;
let changed = 0;
let legacyCleaned = 0;
let swInjected = 0;

for (const file of uniqueFiles) {
  const content = fs.readFileSync(file, 'utf8');
  const hadLegacy = content.includes(LEGACY_FORCE_FRESH_MARKER);
  const hadSw    = content.includes("'serviceWorker' in navigator");
  const processedContent = processHtml(content);

  if (content !== processedContent) {
    changed++;
    if (hadLegacy && !processedContent.includes(LEGACY_FORCE_FRESH_MARKER)) {
      legacyCleaned++;
    }
    if (!hadSw && processedContent.includes("'serviceWorker' in navigator")) {
      swInjected++;
    }
    console.log(`  ${path.relative(__dirname, file)}`);

    if (!isDry) {
      fs.writeFileSync(file, processedContent, 'utf8');
    }
  }
  processed++;
}

// 写 sw.js（要么新写，要么 VERSION 变了就覆盖）
const swPath = path.join(__dirname, 'sw.js');
let swWillChange = true;
if (fs.existsSync(swPath)) {
  const existing = fs.readFileSync(swPath, 'utf8');
  const expected = SW_TEMPLATE.replace('__SW_VERSION__', version);
  swWillChange = existing !== expected;
}
if (swWillChange) {
  writeServiceWorker();
} else {
  console.log(`  sw.js  (unchanged, VERSION=${version})`);
}

console.log(`\n${isDry ? '[DRY RUN] Would change' : 'Changed'} ${changed} of ${processed} HTML files`);
console.log(`Version parameter: ?v=${version}`);
if (legacyCleaned) console.log(`Cleaned legacy cache-buster script from ${legacyCleaned} file(s).`);
if (swInjected)     console.log(`Injected Service Worker registration in ${swInjected} file(s).`);
console.log();

if (isDry) {
  console.log('Run without --dry to apply changes:\n  node build.js\n');
}
